# Generated by Django 6.0.5 on 2026-05-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=100)),
                ("responsavel", models.CharField(max_length=100)),
                ("atividade", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("duracao_dias", models.IntegerField()),
                ("dependencia", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
